name: Tests

on: [pull_request_target]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          token: ${{ secrets.DEPLOY_BOT_TOKEN }}

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.74.3"
          extended: true

      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          start: npm start
          record: true
          wait-on: http://localhost:1313
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
